version: "3.8"

services:

  backend:
    build:
      context: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend


  postgres:
    image: postgres:16
    container_name: devops-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devopsdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
